### ISSUE TITLE
Chapter 1: Overview (formerly known as structure)

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#101]
- Should be written as one of the final things; the report structure is still interchangeable as of now

**Comment by dbdness** [comment]
Denne er nu klar til review, kære @kimmeyera. Der er er ikke så meget til det - et simpelt overblik over alle kapitler og hvad de handler om, således at læseren får sig et tidligt overblik og er klar over hvad der skal til at ske.

Du kan som sædvanligt bare rette og gøre ved - tak!

**Comment by kimmeyera** [comment]
jeg er vild med det boi! Godt skrevet. Det giver et hurtigt uddybet overblik over rapporten! Jeg godkender og lukker!
