### ISSUE TITLE
Chapter 5: Our Tool vs. Holistic Approach

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#103]
- [x] Compare our tool vs. the Holistic approach/algorithms: what is the benefits of our tool? What is the benefit of Holistic?
- [x] Consider and utilize evaluation/comparison techniques; the binary approach (foreign key true/false), confusion matrices or true/false positives and true/false negatives

**Comment by dbdness** [comment]
@kimmeyera så vil jeg mene at denne er klar til review når du har tid, min boy. Som altid retter du bare eller stiller spørgsmål hvis der er noget. Tak! :feelsgood:

**Comment by kimmeyera** [comment]
@dbdness jeg kan rigtig godt lide dette afsnit bror. Det giver rigtig god menining, og får vores tool til at shine 🛡️ Jeg approver!
