### ISSUE TITLE
Chapter 4: Demo

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#106]
Depends on issue #22 

- This section must contain a brief, but thorough, step-by-step instruction/description on how to pull the DockerHub image, run it with docker and start the tool.  

The text from the finished section can preferably be copied to the README as well, closing issue #102

**Comment by dbdness** [comment]
Så er denne sektion i rapporten også klar til review, @kimmeyera. Den kan findes som den sidste del af kapitel 4 som "4.4 Demo". Eksemplerne på connection strings var jeg nødt til at give virkelig lille skriftstørrelse, ellers kunne de ikke være på siden. Det er ærgerligt, men jeg ser ikke nogle andre gode alternativer. Hvis du kan komme på noget, så sig endelig til! Sig også bare til hvis der er noget, eller ret løs på egen hånd. 

Jeg har samtidig taget essensen af hvad der står i rapporten og tilføjet det til vores to READMEs; den i roden og den under docker/ mappen. Jeg har bare lukket #102, da den ikke er så vigtig at reviewe, men du er velkommen til at kaste et blik på de to READMEs hvis du har lyst 😁

**Comment by kimmeyera** [comment]
Det ser skide godt ud bror! Og også vores READMEs! Jeg godkender og lukker!
