### ISSUE TITLE
Improve first chapters of report, based on supervisor input 

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#108]
Checklist:

- [x] A: Remove lists of tables/figures completly 
- [x] B: Introduction, structure: Remove initial text from introduction of "Introduction" chapter 
- [x] C: Chapter 2, Definition of a database (Table, row/record, column, keys, relations (contained relations))
- [x] D: Problem definition is too vague
- [x] E: Move "Goals" elsewhere
- [x] F: Chapter 2, important definitions
- [x] G: Delete subquestions
- [x] H: Motivation, make it more precise + part of the introduction
- [x] I: Explain what is meant by "entity-integrity" in the Primary Key/Codd definiton
- [x] J: Keep this detection-logic in mind and put it somewhere in the report (?), maybe just an issue to start with
- [x] K: Screen recording of tool, make an issue 
- [x] L: Make the repo public (klarede lige denne her @kimmeyera, havde rettigheder til det)
- [x] (More in Majas edit of the document?)

**Comment by kimmeyera** [comment]
@dbdness angående **H**:
Så har jeg rettet teksten min boi. Du må meget gerne lige læse den igennem og rette/tilføje hvis det er. Angående at flytte den, så jeg skrevet det på en kommentar derinde :)

**Comment by dbdness** [comment]
@kimmeyera ift. **H**: 
God sektion, godt skrevet! Jeg har rettet få ord og skrevet en kommentar selv. Jeg har også svaret på dine andre kommentarer derinde 👌

**Comment by kimmeyera** [comment]
@dbdness tak boi - jeg er kommet med modsvar på alle dine kommentarer!

**Comment by dbdness** [comment]
@kimmeyera stærkt, har svaret tilbage igen.

**Comment by kimmeyera** [comment]
@dbdness har kommet med modsvar til dine kommentarer kære!

**Comment by dbdness** [comment]
@kimmeyera og tilbage igen ;)

**Comment by dbdness** [comment]
@kimmeyera ift. **D**: Jeg har nu forsøgt med en ny problemformulering der er blevet en del mere specifik ift. hvor vores research er endt hen. Den ligger inde under den gamle. Vil du reviewe den og side hvad du synes? Du er meget velkommen til at lave ændringer.

**Comment by kimmeyera** [comment]
@dbdness jeg har reviewed den og jeg kan lide den! Godt lavet! :)

**Comment by dbdness** [comment]
@kimmeyera ift. **C**: Jeg har nu rettet lidt tekst og rykket lidt rundt på et par elementer i "Definitions" sektion i kapitel 2, og samtidig skrevet en meget kort forklaring på alle grundbegreberne (keys, columns, rows, tables) indenfor relationel database modellering. Nogle af definitionerne fylder virkelig lidt, og det er med vilje, da vores job kun er at orientere læseren kort, så de kan forstå hvad vi mener når vi nævner begreberne senere.

Du må meget gerne reviewe når du har tid, og du er velkommen til at ændre og smide mere tekst på rundt omkring hvis du synes 🙏

**Comment by kimmeyera** [comment]
@dbdness Har nu læst det igennem og det er kort og præcist skrevet bro! nice work! Synes dog ikke jeg kunne se noget om contained relations? 😢

**Comment by dbdness** [comment]
@kimmeyera Efter vores beslutning på Slack vil jeg nu mene denne issue kan lukkes - er du enig?

**Comment by kimmeyera** [comment]
@dbdness Enig!
