### ISSUE TITLE
Develop Docker container as a testable environment

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#22]
- The container should ship with a MySQL instance, test DB(s) and our integrity checker tool out of the box
- ~~Consider Dockerfile vs. Docker Compose~~ Only a Dockerfile makes sense here, as Docker Compose is used to orchestrate multiple images

___
- [x] Follow the setup procedure of the [updated CLI Tool Wiki page](https://github.com/dbdness/dnikma-thesis-2021/wiki/CLI-Tool) and automate it in the Docker process
- [x] Test the Docker image and container
- [x] Deploy to Docker Hub
- [x] Provide setup guides: #102, #106

**Comment by dbdness** [comment]
Så min kære @kimmeyera, så skulle denne være done og klar til review.

Der er oprettet en ny mappe i roden af løsningen, [docker](https://github.com/dbdness/dnikma-thesis-2021/tree/master/docker), med to filer; en Dockerfile og et startup script. Det står for at hente en lightweight Debian instans, hente dependencies og vores source code, installere test DBs og eksekvere startup scriptet. Startup scriptet i sig selv står for at oprette en container og starte MySQL og dIC i den, så snart imaget køres.

Det er muligt at bygge og eksekvere Docerfilen selv, men det er ikke nødvendigt, da jeg har sat en pipeline op der automatisk bygger og pusher imaget til Docker Hub ved hvert commit til master. Pipeline kan du finde under vores [Github Actions](https://github.com/dbdness/dnikma-thesis-2021/actions).

Derfor er det simpelt og hurtigt at teste hvis du har docker installeret (det kan med fordel være Docker Desktop). Så er det så simpelt som at køre følgende kommando i en terminal:
```
$ docker run -it --pull=always --rm dbdness/dic
```
Her beder du docker om at pulle nyeste version af vores [image fra Docker Hub](https://hub.docker.com/r/dbdness/dic), køre det i en container som interaktiv instans, og slette container igen og rydde op så snart man hopper ud af containeren. 

Du kan bruge de følgende to commands fra dIC til at teste sample dbs direkte fra containeren:
```
root> db-connect connection-string="host=127.0.0.1;database=northwind_nofks;user=demo;password=demo"
root> db-connect connection-string="host=127.0.0.1;database=sakila;user=demo;password=demo"
```

Jeg er gået i gang med at skrive en kort guide i både rapport og README, per issues #102 og #106. Jeg smider en besked inde på dem hver især når det er done.

**Comment by kimmeyera** [comment]
Mega godt arbejde boi!
Jeg kan kun få det til at virke hvis jeg bygger og kører det lokalt med Docker. Det virker ikke hvis jeg pull'er fra Dockerhub som du beskriver her. :(

**Comment by kimmeyera** [comment]
Gelm det. Det virker perfekt!
