### ISSUE TITLE
Chapter 4: Running the CLI tool

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#89]
Points to note, sections to write:

- [x] Overview
- [x] Detecting Potential Foreign Keys (PfkD)
- [x] Detecting Orphaned Records

**Comment by kimmeyera** [comment]
@dbdness så har jeg læst det igennem, og det ser, som altid, skide godt ud! Der var dog 4-5 gange hvor du nævner `orphaned pd` command. Her tænker jeg du mente `orphaned pfkd` command, right? Jeg har ihvertfald rettet det. Hvis det er korrekt rettet, så kan du lukke dette issue og klappe dig selv på skulderen! 🧑‍🏭

**Comment by dbdness** [comment]
Mange tak @kimmeyera, du har helt ret, det var en fejl! 

Tak for review, som altid! 🙏
