### ISSUE TITLE
Chapter 5: Testing Framework

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#91]
- [ ] Check also if Holistic paper mentions their database test scenarios, so we can replicate

**Comment by kimmeyera** [comment]
@dbdness OK boi, så har jeg fyldt noget forberedende hjælpetekst på "5.1 Testing Framework" -afsnittet. Du må meget gerne review det og tilføje/rette som du føler! Tak bror!

**Comment by dbdness** [comment]
Det ser rigtig godt ud som altid, @kimmeyera, godt arbejde! Har kun rettet et par få ord.
Det fremstår rigtig godt som et template til vores kommende test resultater!

**Comment by kimmeyera** [comment]
@dbdness det er jeg rigtig glad for at du synes! Så burde det være lige til at gå i gang med testene, når vi får adgang til databasen. 📅

**Comment by kimmeyera** [comment]
@dbdness Så er dette afsnit vel klar til review kære! Jeg kan se at du er gået i gang!

**Comment by dbdness** [comment]
Det er jeg gode, og jeg synes det er så godt arbejde! 
Jeg har kun rettet et par enkelte småting som ordstillinger og små-grammatik. Jeg har lige smidt en sidste kommentar til dig under "5.1.5    Concluding the Validation Testing", men den kan vi fortsætte derinde i dokumentet. Jeg lukker her 🎉
