### ISSUE TITLE
Chapter 5: Limitations

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#92]

**Comment by dbdness** [comment]
Så skulle denne langt om længe være klar til review, kære @kimmeyera. Jeg har forsøgt at holde det så kort og præcist som muligt, uden at foreslå mulige løsninger - det må reflection- og future work sektionerne klare :grin:

Du er som altid velkommen til at rette, tilføje eller slette. Thank you!

**Comment by kimmeyera** [comment]
@dbdness det ser skide godt ud. Vi har aftalt at lade den ene kommentar stå, som du har skrevet. Jeg closer denne 🧛 🧛‍♀️
