### ISSUE TITLE
Chapter 6: Future Work

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#95]

**Comment by kimmeyera** [comment]
Future Work ide fra Maja: 
"Detektering af primary keys, hav denne overvejelse med → Hvis to columns er unikke og antages som potential primary key, og en/flere andre columns kun refererer til den ene af de to ppks, så burde den anden teoretisk kunne skrælles væk som støj"

**Comment by dbdness** [comment]
@kimmeyera jeg har nu ændret lidt i opsætningen på denne, tilføjet paragraffer, justeret lidt i teksten og tilføjet noget nyt.

Du må meget gerne reviewe når du har tid, og endelig bare rette løs. Hvis du har flere ideer til future work der er så interessante at de skal med her, så sig meget gerne til.

**Comment by kimmeyera** [comment]
@dbdness det ser godt ud boi, jeg godkender! 
Jeg har kun lagt en enkel kommentar på din kommentar derinde! jeg lukker denne 🌵
