### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by dbdness** [dbdness/dnikma-thesis-2021#96]
- [x] Appendix A, CLI Tool overview: (ONLY A SUBSET OF MOST IMPORTANT FEATURES INCLUDED) Review and update both the working document and the copy in the report while at it (?)
- [x] Appendix B
- [x] Appendix D
- [x] Appendix E
- [x] ?

**Comment by kimmeyera** [comment]
@dbdness så tror jeg kun vi mangler den video du laver, som appendix bror!

**Comment by dbdness** [comment]
@kimmeyera Done!

**Comment by dbdness** [comment]
Husk at inkludere PDFs i bilag igen efter rettelser!
